plugins:
  rating_show_topic_tip:
    default: true
    client: true
  rating_show_exact_average:
    default: true
    client: true
  rating_tags:
    client: true
    type: list
    default: 'rating'
